"use client";
import { BlogpostForm } from "@/components/BlogpostForm";
import { Blogposts } from "@/components/Blogposts";
import Login from "@/components/Login";
import { BlogPost } from "@/utils/types";
import { useEffect, useState } from "react";

export default function Home() {
  const [blogposts, setBlogposts] = useState<BlogPost[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isLoggedIn, setIsLoggedIn] = useState<boolean>(false);

  useEffect(() => {
    const fetchBlogPosts = async () => {
      const token = localStorage.getItem("token");
      if (token) setIsLoggedIn(true);
      try {
        const res = await fetch("http://localhost:5000/blogposts/all", {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });
        if (!res.ok) {
          throw Error(`Error: ${res.statusText}`);
        }
        const data: BlogPost[] = await res.json();
        setBlogposts(data);
      } catch (error: any) {
        setIsLoggedIn(false);
        setError(error);
      } finally {
        setLoading(false);
      }
    };

    fetchBlogPosts();
  }, []);

  if (loading) {
    return <p className="text-lg text-gray-500">Loading...</p>;
  }

  if (!isLoggedIn) {
    return (
      <div className="min-h-screen bg-gray-100 p-6">
        <h1 className="text-3xl font-bold mb-4">Blog Author Frontend</h1>
        <p className="text-gray-600 mb-6">
          Please login to view and add blogposts
        </p>
        <Login />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-100 p-6">
      <h1 className="text-3xl font-bold mb-4">Blog Author Frontend</h1>
      <p className="text-gray-600 mb-6">Generated by create next app</p>

      <BlogpostForm
        setBlogposts={setBlogposts}
        blogposts={blogposts}
        setError={setError}
      />

      {loading && <p className="text-lg text-gray-500">Loading...</p>}
      {error && <p className="text-red-500">{error}</p>}

      <Blogposts
        blogposts={blogposts}
        setBlogposts={setBlogposts}
        setError={setError}
      />
    </div>
  );
}
